#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# chkconfig: 345 02 02
# description: If the NAND doesn't have enough free space, set up a VT for\
#              diskspacerecover.
# processname: diskspacecheck

# Author:      Chris Ball <cjb@laptop.org>

import os, sys, statvfs, pyvt, time

THRESHOLD = 1024 * 20  # 20MB
DATASTORE_PATH = "/home/olpc/.sugar/default/datastore/store/*-*"
ACTIVITY_PATH  = "/home/olpc/Activities/*"

# Determine free space on /.
stat = os.statvfs("/")
freebytes  = stat[statvfs.F_BSIZE] * stat[statvfs.F_BAVAIL]
freekbytes = freebytes / 1024

# If we have enough disk space, exit.
if freekbytes > THRESHOLD:
    exit

# Disable pretty-boot.
if os.system("ps awux | grep 0-boot-anim-start | grep -v grep") == 0:
    # Pretty-boot is running.  Kill it, and set up a new VT for the next script.
    os.system("/etc/init.d/z-boot-anim-stop start")
    pyvt.chcon("/dev/tty1")
    pyvt.chcon("/dev/console")
    pyvt.chvt(2)

# Don't think there's anything useful I can do if this write fails.
dcon = open('/sys/class/backlight/dcon-bl/device/freeze', 'w')
dcon.write('0')
dcon.close()
os.system("/sbin/setsysfont")
os.system("/bin/unicode_start sun12x22")
