#!/bin/sh
#
# This script comes from:
#
#   commit 7835ca9c79bfc3d8c1d5d64da6815a3c13ddcd48
#   Author: C. Scott Ananian <cscott@laptop.org>
#   Date:   Wed Nov 28 01:22:43 2007 -0500
#
#      olpc-network-capture (trac #5153).
#

SECS=30
CAPTURE_FILE=`date +%y%m%d%H%M`.cap
TRAFFIC_MASK=0x7

echo "Capturing traffic for $SECS seconds..."
killall NetworkManager
sleep 1
echo $TRAFFIC_MASK > /sys/class/net/eth0/lbs_rtap
ifconfig rtap0 up
tcpdump -s 128 -i rtap0 -w $CAPTURE_FILE &> /dev/null &
PID=$!
sleep $SECS
kill $PID
echo "Done.  Capture file is $CAPTURE_FILE"
NetworkManager
