#!/bin/sh
#
# Author: Richard Smith <richard@laptop.org>
#
DATE=`date "+%y%m%d-%H%M%S"`
USER=`grep ickname /home/olpc/.sugar/default/config |cut -f 2 -d = |awk '{sub("^ ","",$0); print $0}'`
LOGFILE="log-$USER-$DATE.csv"
B_INFO=/sys/class/power_supply/olpc-battery
echo "logbat Ver: 1.0" > $LOGFILE
echo `cat /ofw/ec-name` >> $LOGFILE
echo `cat /ofw/model` >> $LOGFILE
echo `cat $B_INFO/technology` >> $LOGFILE
echo `cat $B_INFO/serial_number` >> $LOGFILE
echo `cat /boot/olpc_build` >> $LOGFILE

while true
do
	CAP=`cat $B_INFO/capacity`
	VOLT=`cat $B_INFO/voltage_avg`
	CURR=`cat $B_INFO/current_avg`
	TEMP=`cat $B_INFO/temp`
	ACR=`cat $B_INFO/accum_current`
	STAT=`cat $B_INFO/status`
	CAPLEVEL=`cat $B_INFO/capacity_level`
	echo `date +%s`",$CAP,$VOLT,$CURR,$TEMP,$ACR,$STAT,$CAPLEVEL" | tee -a $LOGFILE
	sync
	sleep 10
done
