#!/bin/bash
#
# olpc-configure       Perform one-time configuration
#
# chkconfig: 345 01 01
# description: olpc-configure performs one-time configuration
# processname: olpc-configure

OLPC_HOME=/home/olpc

# load alsa configuration here since doing it at module load time wasn't working
/usr/sbin/alsactl restore

if [ -x /usr/sbin/olpc-bios-sig ] ; then
    if [ "`/usr/sbin/olpc-bios-sig | cut -c 7-8`" = "Q2" ] ; then
        # Libertas Marvell LED configuration
        # map LED1 to GPIO1, LED2 to GPIO12, LED3 to GPIO16
        /sbin/iwpriv eth0 ledgpio 1 1 2 12 3 16 > /dev/null
    fi
fi 

# exit if first boot configurations are already done
if [ -e $OLPC_HOME/.olpc-configured ] ; then
    exit 0
fi

read_nvram() {
    dd if=/dev/nvram bs=1 skip=$(($1)) count=$2 2>/dev/null
}

# Some defaults
XORG_CONF=xorg-emu.conf
XKB_LAYOUT="us"
SYS_LANG="en_US.UTF-8"
KERN_KEYTABLE="us"

if [ "$(grep -i geode /proc/cpuinfo | wc -l)" != "0" ] ; then
    # TODO: put this all in a hal callout or something similar
    XORG_CONF=xorg-dcon.conf

    # on A test boards exit here
    BUILD_HEADER=`read_nvram 0x42 1`
    [ "x$BUILD_HEADER" = "xA" -o "x$BUILD_HEADER" = "x" ] && exit 0

    if [ "`/usr/sbin/olpc-bios-sig | cut -c 7-8`" = "Q2" ] ; then
        #
        # TODO: this ugly table has to go away when we'll get this info right
        # from the manufacturing data (starting with C2, probably).  -- bernie
        #
        # TODO: maybe set the kernel keytable accordingly -- bernie again
        #
        KB_HEADER=`read_nvram 0x44 2`
        if [ "x$KB_HEADER" = "xKB" ] ; then
            KB_CODE=`read_nvram 0x46 10`
            if [ "x$KB_CODE" = "xus_INTL" ] ; then
                XKB_LAYOUT="us"
            elif [ "x$KB_CODE" = "xes" ] ; then
                XKB_LAYOUT="es"
                SYS_LANG="es_AR.UTF-8"
            elif [ "x$KB_CODE" = "xpt_BR" ] ; then
                XKB_LAYOUT="br"
                SYS_LANG="pt_BR.UTF-8"
            elif [ "x$KB_CODE" = "xara" ] ; then
                XKB_LAYOUT="us(olpc2),ara(olpc)"
                SYS_LANG="ar_LY.UTF-8"
            elif [ "x$KB_CODE" = "xth" ] ; then
                XKB_LAYOUT="us(olpc2),th(olpc)"
                SYS_LANG="th_TH.UTF-8"
            elif [ "x$KB_CODE" = "xng" ] ; then
                XKB_LAYOUT="ng(olpc)"
            elif [ "x$KB_CODE" = "xpk" ] ; then
                XKB_LAYOUT="us(olpc2),ur(olpc)"
                SYS_LANG="ur_PK.UTF-8"
            elif [ "x$KB_CODE" = "xet" ] ; then
                XKB_LAYOUT="us(olpc2),et"
                SYS_LANG="am_ET.UTF-8"
            fi
        fi
    fi
fi

cd /etc/X11
rm -f xorg.conf
ln -sf $XORG_CONF xorg.conf

cat >$OLPC_HOME/.i18n <<__EOF__
LANG="$SYS_LANG"
XKB_LAYOUT="$XKB_LAYOUT"
__EOF__
chown olpc:olpc $OLPC_HOME/.i18n

# LANG=C speeds up boot considerably (measured 5sec) -- bernie
cat >/etc/sysconfig/i18n <<__EOF__
LANG=C
SYS_FONT=sun12x22
__EOF__

cat >/etc/sysconfig/keyboard <<__EOF__
KEYTABLE="$KERN_KEYTABLE"
__EOF__

touch $OLPC_HOME/.olpc-configured
