#!/bin/sh

FILEPATH="/root"
LOGFILE="/pwr_prof.csv"
B_INFO=/sys/class/power_supply/olpc-battery

STAT=`cat $B_INFO/status`
AC_STAT=`cat /sys/class/power_supply/olpc-ac/online`

# If we are on AC then only log if we are charging
if [ $AC_STAT == "1" -a $STAT != "Charging" ]
then
	exit 0
fi

# if the file does not exist then create it
if [ ! -e "$FILEPATH$LOGFILE" ]
then
	echo "olpc-pwr-prof: Ver: 1.0" > $FILEPATH$LOGFILE
	echo `cat /ofw/ec-name` >> $FILEPATH$LOGFILE
	echo `cat /ofw/model` >> $FILEPATH$LOGFILE
	echo `cat /ofw/openprom/model` >> $FILEPATH$LOGFILE
	echo `cat $B_INFO/technology` >> $FILEPATH$LOGFILE
	echo `cat $B_INFO/serial_number` >> $FILEPATH$LOGFILE
	echo `cat /boot/olpc_build` >> $FILEPATH$LOGFILE
fi

	CAP=`cat $B_INFO/capacity`
	VOLT=`cat $B_INFO/voltage_avg`
	CURR=`cat $B_INFO/current_avg`
	TEMP=`cat $B_INFO/temp`
	ACR=`cat $B_INFO/accum_current`
	CAPLEVEL=`cat $B_INFO/capacity_level`
	echo `date +%s`",$CAP,$VOLT,$CURR,$TEMP,$ACR,$STAT,$CAPLEVEL" >> $FILEPATH$LOGFILE
